"""
Tests Alembic migrations against a real throwaway SQLite database (Feature F).
Verifies: (1) `alembic upgrade head` builds the complete schema from empty,
(2) it is idempotent/safe to run twice, (3) the resulting tables match the
live ORM metadata so migrations can't silently drift from the models.
"""
import subprocess
import sys
from pathlib import Path

import pytest
from sqlalchemy import create_engine, inspect

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
BACKEND_ROOT = REPO_ROOT / "backend"


def _run_alembic(db_path: Path, *args: str):
    env = {"DATABASE_URL": f"sqlite:///{db_path}", "PATH": "/usr/bin:/bin"}
    import os

    full_env = {**os.environ, **env}
    result = subprocess.run(
        [sys.executable, "-m", "alembic", "-c", str(BACKEND_ROOT / "alembic.ini"), *args],
        cwd=BACKEND_ROOT,
        env=full_env,
        capture_output=True,
        text=True,
    )
    return result


@pytest.fixture
def fresh_db_path(tmp_path):
    return tmp_path / "alembic_test.db"


def test_upgrade_head_builds_full_schema_from_empty(fresh_db_path):
    result = _run_alembic(fresh_db_path, "upgrade", "head")
    assert result.returncode == 0, result.stderr

    engine = create_engine(f"sqlite:///{fresh_db_path}")
    tables = set(inspect(engine).get_table_names())

    expected_tables = {
        "users", "payers", "providers", "claims", "claim_lines", "denial_events",
        "appeal_events", "recovery_outcomes", "model_versions", "model_predictions",
        "model_metrics", "drift_metrics", "documents", "document_chunks",
        "rag_retrievals", "workflow_actions", "human_reviews", "audit_logs",
        "synthetic_data_runs", "background_jobs", "alembic_version",
    }
    assert expected_tables.issubset(tables)


def test_upgrade_head_is_idempotent(fresh_db_path):
    first = _run_alembic(fresh_db_path, "upgrade", "head")
    assert first.returncode == 0, first.stderr
    second = _run_alembic(fresh_db_path, "upgrade", "head")
    assert second.returncode == 0, second.stderr


def test_migrated_schema_matches_orm_metadata(fresh_db_path):
    """The migration-built schema's table set must match what Base.metadata
    would create directly -- guards against migrations drifting from models."""
    sys.path.insert(0, str(BACKEND_ROOT))
    from app.core.database import Base  # noqa: E402

    result = _run_alembic(fresh_db_path, "upgrade", "head")
    assert result.returncode == 0, result.stderr

    engine = create_engine(f"sqlite:///{fresh_db_path}")
    migrated_tables = set(inspect(engine).get_table_names()) - {"alembic_version"}
    orm_tables = set(Base.metadata.tables.keys())
    assert migrated_tables == orm_tables


def test_downgrade_then_upgrade_round_trips(fresh_db_path):
    up = _run_alembic(fresh_db_path, "upgrade", "head")
    assert up.returncode == 0, up.stderr

    down = _run_alembic(fresh_db_path, "downgrade", "base")
    assert down.returncode == 0, down.stderr

    engine = create_engine(f"sqlite:///{fresh_db_path}")
    tables = set(inspect(engine).get_table_names()) - {"alembic_version"}
    assert tables == set()

    up_again = _run_alembic(fresh_db_path, "upgrade", "head")
    assert up_again.returncode == 0, up_again.stderr


def test_embedding_vector_dimension_matches_orm_model():
    """
    Regression test for a real bug: the initial migration was
    autogenerated as `Vector()` (no explicit dim), which silently fell
    back to the Vector TypeDecorator's class default of 1536 -- while the
    ORM model (app/models/domain.py) declares `Vector(384)`, matching the
    default mock embedding provider's actual output dimension
    (rag/embeddings.py:EMBEDDING_DIM). SQLite stores embeddings as
    untyped JSON and never enforces a dimension, so this drift was
    completely invisible until tested against real pgvector, which
    rejected every insert with "expected 1536 dimensions, not 384".
    This test parses the migration file's source directly so it fails
    loudly if a future autogenerate reintroduces the bare `Vector()` form.
    """
    migration_path = Path(__file__).resolve().parent.parent / "alembic" / "versions" / "963bd6481f13_initial_schema.py"
    source = migration_path.read_text()
    assert "Vector(dim=384)" in source, (
        "Migration must explicitly declare the embedding column's vector "
        "dimension (384, matching app/models/domain.py and "
        "rag/embeddings.py:EMBEDDING_DIM) -- a bare Vector() silently "
        "defaults to 1536 and breaks on real pgvector."
    )


def test_vector_type_repr_preserves_dimension():
    """
    Regression test for the ROOT CAUSE of the above bug: Vector.__repr__
    must reconstruct the actual `dim` the instance was created with, since
    this is exactly what Alembic's autogenerate calls when rendering a
    column's type into a migration file. Without a correct __repr__,
    autogenerate silently loses the dim argument on every future migration
    that touches a Vector column, not just this one.
    """
    from app.models.types import Vector

    assert repr(Vector(dim=384)) == "Vector(dim=384)"
    assert repr(Vector(dim=1536)) == "Vector(dim=1536)"
    assert repr(Vector()) == "Vector(dim=1536)"  # class default, made explicit rather than silent


def test_document_chunk_orm_model_dimension_matches_default_embedding_provider():
    """
    Direct cross-check that the two independently-declared dimensions
    (ORM column, embedding provider output) actually agree -- this is
    exactly the invariant whose violation caused the original bug. If
    either side changes without the other, this test catches it before a
    real Postgres deployment does.
    """
    from app.models.domain import DocumentChunk
    from app.rag.embeddings import EMBEDDING_DIM

    embedding_col = DocumentChunk.__table__.columns["embedding"]
    assert embedding_col.type.dim == EMBEDDING_DIM
