FROM node:20-slim AS base

WORKDIR /app
COPY frontend/package.json frontend/package-lock.json* /app/
RUN npm install

COPY frontend /app
ENV NEXT_TELEMETRY_DISABLED=1

EXPOSE 3000
CMD ["npm", "run", "dev"]
