"""initial schema

Revision ID: 963bd6481f13
Revises: 
Create Date: 2026-08-24 09:46:54.322217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.types


# revision identifiers, used by Alembic.
revision: str = '963bd6481f13'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('background_jobs',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('task_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_versions',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('version_tag', sa.String(length=50), nullable=False),
    sa.Column('artifact_path', sa.String(length=255), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('feature_names', sa.JSON(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('dataset_version', sa.String(length=50), nullable=True),
    sa.Column('feature_schema_version', sa.String(length=20), nullable=False),
    sa.Column('calibration_status', sa.String(length=20), nullable=False),
    sa.Column('is_champion', sa.Boolean(), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_type', 'version_tag', name='uq_model_type_version')
    )
    op.create_table('payers',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('payer_type', sa.String(length=50), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('data_source', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('providers',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('npi', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('data_source', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('npi')
    )
    op.create_table('synthetic_data_runs',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('dataset_version', sa.String(length=50), nullable=False),
    sa.Column('generator_version', sa.String(length=20), nullable=False),
    sa.Column('generation_seed', sa.Integer(), nullable=False),
    sa.Column('run_params', sa.JSON(), nullable=False),
    sa.Column('records_created', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'REVIEWER', 'BILLER', 'ANALYST', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('claims',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('claim_number', sa.String(length=50), nullable=False),
    sa.Column('provider_id', app.models.types.GUID(), nullable=False),
    sa.Column('payer_id', app.models.types.GUID(), nullable=False),
    sa.Column('patient_ref', sa.String(length=50), nullable=False),
    sa.Column('claim_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('claim_type', sa.String(length=30), nullable=False),
    sa.Column('place_of_service', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'PAID', 'DENIED', 'APPEALED', 'RECOVERED', 'CLOSED', name='claimstatus'), nullable=False),
    sa.Column('eligibility_status', sa.String(length=20), nullable=False),
    sa.Column('authorization_status', sa.String(length=20), nullable=False),
    sa.Column('documentation_completeness', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('service_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submission_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timely_filing_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('data_source', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['payer_id'], ['payers.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_number')
    )
    op.create_table('documents',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('payer_id', app.models.types.GUID(), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['payer_id'], ['payers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drift_metrics',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('model_version_id', app.models.types.GUID(), nullable=True),
    sa.Column('metric_type', sa.String(length=30), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('feature_name', sa.String(length=100), nullable=True),
    sa.Column('baseline_value', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('current_value', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('drift_score', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_drift_detected', sa.Boolean(), nullable=False),
    sa.Column('reference_period', sa.String(length=100), nullable=False),
    sa.Column('current_period', sa.String(length=100), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_metrics',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('model_version_id', app.models.types.GUID(), nullable=False),
    sa.Column('metric_name', sa.String(length=50), nullable=False),
    sa.Column('metric_value', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.String(length=100), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('claim_id', app.models.types.GUID(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claim_lines',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('claim_id', app.models.types.GUID(), nullable=False),
    sa.Column('procedure_code', sa.String(length=10), nullable=False),
    sa.Column('diagnosis_code', sa.String(length=10), nullable=False),
    sa.Column('modifiers', sa.String(length=50), nullable=False),
    sa.Column('line_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('denial_events',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('claim_id', app.models.types.GUID(), nullable=False),
    sa.Column('denial_reason_code', sa.String(length=50), nullable=False),
    sa.Column('denial_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_reason_text', sa.Text(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_chunks',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('document_id', app.models.types.GUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('embedding', app.models.types.Vector(dim=384), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_predictions',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('claim_id', app.models.types.GUID(), nullable=False),
    sa.Column('model_version_id', app.models.types.GUID(), nullable=False),
    sa.Column('prediction_type', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=True),
    sa.Column('explanation', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recovery_outcomes',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('claim_id', app.models.types.GUID(), nullable=False),
    sa.Column('expected_recovery', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('actual_recovery', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_actions',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('claim_id', app.models.types.GUID(), nullable=False),
    sa.Column('action_type', sa.Enum('VERIFY_ELIGIBILITY', 'OBTAIN_AUTHORIZATION', 'REQUEST_DOCUMENTATION', 'CORRECT_CODING', 'RESUBMIT', 'APPEAL', 'CONTACT_PAYER', 'ESCALATE', 'STOP_RECOVERY', 'DRAFT_APPEAL', name='workflowactiontype'), nullable=False),
    sa.Column('recommended_by', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'EXECUTED', name='workflowactionstatus'), nullable=False),
    sa.Column('created_by', app.models.types.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appeal_events',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('denial_event_id', app.models.types.GUID(), nullable=False),
    sa.Column('appeal_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('recovered_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('decision_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['denial_event_id'], ['denial_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('human_reviews',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('workflow_action_id', app.models.types.GUID(), nullable=False),
    sa.Column('reviewer_id', app.models.types.GUID(), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workflow_action_id'], ['workflow_actions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rag_retrievals',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('appeal_draft_id', app.models.types.GUID(), nullable=False),
    sa.Column('document_chunk_id', app.models.types.GUID(), nullable=False),
    sa.Column('similarity_score', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['appeal_draft_id'], ['workflow_actions.id'], ),
    sa.ForeignKeyConstraint(['document_chunk_id'], ['document_chunks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rag_retrievals')
    op.drop_table('human_reviews')
    op.drop_table('appeal_events')
    op.drop_table('workflow_actions')
    op.drop_table('recovery_outcomes')
    op.drop_table('model_predictions')
    op.drop_table('document_chunks')
    op.drop_table('denial_events')
    op.drop_table('claim_lines')
    op.drop_table('audit_logs')
    op.drop_table('model_metrics')
    op.drop_table('drift_metrics')
    op.drop_table('documents')
    op.drop_table('claims')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('synthetic_data_runs')
    op.drop_table('providers')
    op.drop_table('payers')
    op.drop_table('model_versions')
    op.drop_table('background_jobs')

    # Postgres auto-creates a named ENUM TYPE for each Enum() column
    # (userrole, claimstatus, workflowactiontype, workflowactionstatus);
    # op.drop_table() does NOT drop these automatically, so a bare
    # downgrade leaves orphaned types behind that then collide with
    # CREATE TYPE on the next upgrade ("type already exists"). SQLite has
    # no native enum type (stored as a plain VARCHAR CHECK constraint), so
    # this only ever surfaces against real Postgres -- explicitly dropping
    # them here (checkfirst=True so this migration still no-ops cleanly on
    # SQLite, which doesn't have named enum types to drop) closes that gap.
    from sqlalchemy.dialects.postgresql import ENUM as PG_ENUM

    bind = op.get_bind()
    for enum_name in ("userrole", "claimstatus", "workflowactiontype", "workflowactionstatus"):
        PG_ENUM(name=enum_name).drop(bind, checkfirst=True)
    # ### end Alembic commands ###
